/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemaTienda;

import claseConectar.Dominio;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Point;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Ezenic
 */
public class BuscarFacturaVenta extends javax.swing.JInternalFrame {

     DefaultTableModel model;
     Principal p;
    public BuscarFacturaVenta(Principal p) {
        initComponents();
        this.p = p;
        Dominio.centrarDatos(tfacturas);
        this.setLocation((this.p.getSize().width/2)-(this.getWidth()/2), (this.p.getSize().height/2)-(this.getHeight()/2));       
        cargar("",null,null);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        cantidad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfacturas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        mostrar = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        facturaRadio = new javax.swing.JRadioButton();
        nombreRadio = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        hasta = new com.toedter.calendar.JDateChooser();
        desde = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jMenuItem1.setText("Eliminar Factura");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CONSULTAS FACTURAS DE VENTA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Facturas de Venta"));
        jPanel1.setToolTipText("");

        cantidad.setText("Cantidad de Facturas de Ventas: 0");

        tfacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Número", "Sucursal", "Cliente ", "Forma de Pago", "Comprobante", "Descuento", "Motivo", "Total", "Estado", "Entregado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tfacturas.setComponentPopupMenu(jPopupMenu1);
        tfacturas.getTableHeader().setReorderingAllowed(false);
        tfacturas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tfacturasMouseMoved(evt);
            }
        });
        tfacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfacturasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tfacturas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cantidad)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Factura de Venta"));

        mostrar.setText("Mostrar Todos");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarKeyTyped(evt);
            }
        });

        buttonGroup1.add(facturaRadio);
        facturaRadio.setSelected(true);
        facturaRadio.setText("Buscar por Número Factura");
        facturaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(nombreRadio);
        nombreRadio.setText("Buscar por Nombre Cliente");
        nombreRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRadioActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setText("Buscar por Fecha");

        hasta.setDate(new Date());
        hasta.setMinSelectableDate(new java.util.Date(-62135755099000L));
        hasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hastaPropertyChange(evt);
            }
        });

        desde.setBackground(new java.awt.Color(255, 0, 51));
        desde.setForeground(java.awt.Color.blue);
        desde.setToolTipText("");
        desde.setDate(new Date());
        desde.setMinSelectableDate(new java.util.Date(-62135755099000L));
        desde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                desdeMouseReleased(evt);
            }
        });
        desde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                desdePropertyChange(evt);
            }
        });

        jLabel2.setText("Desde");

        jLabel3.setText("Hasta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facturaRadio)
                            .addComponent(nombreRadio))
                        .addGap(27, 27, 27)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1286, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(desde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(facturaRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreRadio)))
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_desdePropertyChange
        if (desde.getDate().after(hasta.getDate())){
            hasta.setDate(desde.getDate());
        }
        cargar("",desde.getDate(),hasta.getDate());
    }//GEN-LAST:event_desdePropertyChange

    private void desdeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desdeMouseReleased

    }//GEN-LAST:event_desdeMouseReleased

    private void hastaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_hastaPropertyChange
       if (hasta.getDate().before(desde.getDate())){
            desde.setDate(hasta.getDate());
        }
        cargar("",desde.getDate(),hasta.getDate());
    }//GEN-LAST:event_hastaPropertyChange

    private void nombreRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreRadioActionPerformed

    private void facturaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaRadioActionPerformed

    }//GEN-LAST:event_facturaRadioActionPerformed

    private void buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyTyped
       if (buscar.getText().length() == Dominio.DOM_NOMBRES){
            evt.consume();
        }
    }//GEN-LAST:event_buscarKeyTyped

   public void cargar(String valor, Date de, Date ha){
     tfacturas.getColumnModel().getColumn(1).setCellRenderer(new TableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, final Object value, boolean arg2,
                boolean arg3, int arg4, int arg5) {
            final JLabel lab = new JLabel("<html><a href=\"" + value + "\">" + value + "</a>");
            return lab;
        }
    });
          
    String consulta="";
    String []Registros=new String[11];
    model= (DefaultTableModel) tfacturas.getModel();
    model = Dominio.eliminarTabla(model); 
        try {
              ResultSet rsfactura = null;
              String querySucursal = "";
              if (!this.p.usuarioLogueado.getRol().equals(Constantes.ROL_ADMIN)){
                   querySucursal = " and s.nombre = '"+this.p.usuarioLogueado.getSucursal()+"' ";
              }
              
              if (de==null && ha ==null){ //Busca todo o por nombre 
                  if(facturaRadio.isSelected()){
                       consulta="SELECT f.fecha, f.id_factura,s.nombre, c.nombre,f.forma_pago,f.comprobante,f.motivo,f.total,f.estado,f.entregado FROM facturas as f inner join misclientes as c on f.id_mcliente = c.id_mcliente inner join sucursales as s on s.id_sucursal = f.id_sucursal WHERE concat(f.id_factura) LIKE '%"+valor+"%' and f.eliminado = '0' "+querySucursal+" order by f.fecha,f.id_factura";
                    }
                  if(nombreRadio.isSelected()){
                      consulta="SELECT f.fecha, f.id_factura,s.nombre, c.nombre,f.forma_pago,f.comprobante,f.motivo,f.total,f.estado,f.entregado FROM facturas as f inner join misclientes as c on f.id_mcliente = c.id_mcliente inner join sucursales as s on s.id_sucursal = f.id_sucursal WHERE lower(c.nombre) LIKE '%"+valor.toLowerCase()+"%' and f.eliminado = '0' "+querySucursal+"  order by f.fecha,f.id_factura";
                    }
              }else{
                 consulta="SELECT f.fecha, f.id_factura,s.nombre, c.nombre,f.forma_pago,f.comprobante,f.motivo,f.total,f.estado,f.entregado FROM facturas as f inner join misclientes as c on f.id_mcliente = c.id_mcliente inner join sucursales as s on s.id_sucursal = f.id_sucursal WHERE  f.fecha>='"+de+"' and f.fecha <='"+ha+"' and f.eliminado = '0' "+querySucursal+" order by f.fecha,f.id_factura";
              }
              rsfactura = this.p.bd.mostrarFacturasVentas(consulta); //toma fila por fila 
              while(rsfactura.next())
              {
                  Registros[0]= Dominio.formatofechaJCalender.format(Dominio.formatofechaBD.parse(rsfactura.getString(1)));
                  Registros[1]= rsfactura.getString(2);  //id_factura
                  Registros[2]=rsfactura.getString(3);  //nombre sucursal
                  Registros[3]=rsfactura.getString(4);  //nombre cliente
                  Registros[4]=rsfactura.getString(5);  //forma 
                  Registros[5]=rsfactura.getString(6);  //comprobante
                  Registros[6]= Dominio.A2Decimales(this.p.bd.obtenerPromedioDeDescuentos(rsfactura.getString(2)));//oBTIENE Descuentos totales             
                  Registros[7]=rsfactura.getString(7); //motivo
                  Registros[8]= Dominio.A2Decimales(rsfactura.getString(8)); //total 
                  Registros[9]=rsfactura.getString(9); //estado
                  Registros[10]=Dominio.A2Decimales(rsfactura.getString(10)); //entregado
                  model.addRow(Registros);      
              }
              tfacturas.setModel(model);  
        } catch (SQLException ex) {
            Logger.getLogger(BuscarFacturaVenta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
             Logger.getLogger(BuscarFacturaVenta.class.getName()).log(Level.SEVERE, null, ex);
         }
    cantidad.setText("Cantidad de Facturas de Ventas: "+tfacturas.getRowCount());
  }  
    
   
    
    
    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
         cargar(buscar.getText(),null,null);
    }//GEN-LAST:event_buscarKeyReleased

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

    }//GEN-LAST:event_buscarActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
              try {
            ResultSet rsFecha = this.p.bd.obtenerFechaMinimaYMaxima(); //toma fila por fila
            if (rsFecha.next()){
                desde.setDate(Dominio.formatofechaBD.parse(rsFecha.getString(1)));
                hasta.setDate(Dominio.formatofechaBD.parse(rsFecha.getString(2)));
                cargar(null,desde.getDate(),hasta.getDate());
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(BuscarFacturaVenta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(BuscarFacturaVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mostrarActionPerformed

    private void tfacturasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfacturasMouseMoved
         int col = tfacturas.columnAtPoint(new Point(evt.getX(), evt.getY()));
            if (col == 1) {             
                tfacturas.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }else{
                tfacturas.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }        // TODO add your handling code here:
    }//GEN-LAST:event_tfacturasMouseMoved

    private void tfacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfacturasMouseClicked
            int col = tfacturas.columnAtPoint(new Point(evt.getX(), evt.getY()));
            if (col==1){
                try {
                    int fila = tfacturas.rowAtPoint(new Point(evt.getX(), evt.getY()));
                    String id_factura = (String) tfacturas.getModel().getValueAt(fila, 1);
                    DetalleFacturaVenta det = new DetalleFacturaVenta(this,this.p,id_factura);
                    this.p.escritorio.add(det);
                    det.show();
                    det.setMaximum(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(BuscarFacturaVenta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                    // TODO add your handling code here:*/
    }//GEN-LAST:event_tfacturasMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         if (tfacturas.getSelectedRow()== -1){
           JOptionPane.showMessageDialog(this,"No ha seleccionado ningún Producto","Advertencia", JOptionPane.WARNING_MESSAGE); //Tipo de mensaje 
         }else{
           model =  (DefaultTableModel) tfacturas.getModel();
           int fila = tfacturas.getSelectedRow();
               String id_factura = model.getValueAt(fila,1).toString();
               String estado = model.getValueAt(fila,8 ).toString();
               String comprobante = model.getValueAt(fila,4).toString();
               int opcion;
               if (estado.equals("PAGADO")){
                   opcion=JOptionPane.showInternalConfirmDialog(this, "¿Desea eliminar la factura?" );
               }else{
                   opcion=JOptionPane.showInternalConfirmDialog(this, "Advertencia: la factura no ha sido pagada. ¿Desea eliminar la factura de todas formas?. " );
               }
               if (JOptionPane.OK_OPTION ==opcion ){   
                  int n=this.p.bd.eliminarFacturaVenta(id_factura);
                   if (n>0){
                     JOptionPane.showMessageDialog(this,"La factura ha sido eliminada","Eliminar Factura", JOptionPane.INFORMATION_MESSAGE); //Tipo de mensaje
                     cargar("",desde.getDate(),hasta.getDate());
                     ResultSet rsfactura = this.p.bd.obtenerCantidadPorArticuloYTalle(id_factura);
                     String id_articulo,cant, id_talle, id_sucursal;
                      try {
                          while(rsfactura.next())
                          {  
                            id_articulo = rsfactura.getString(1);
                            id_talle = rsfactura.getString(2);
                            cant = rsfactura.getString(3);
                            id_sucursal = rsfactura.getString(4);
                            if (comprobante.equals("Factura")){
                               this.p.bd.actualizarStockArticulosPorIdTalleYIdSucursal("-"+cant,id_articulo, id_talle, id_sucursal);
                            }else{
                                System.out.println(cant);
                               this.p.bd.actualizarStockArticulosPorIdTalleYIdSucursal(cant,id_articulo, id_talle, id_sucursal); 
                            }
                          }
                      } catch (SQLException ex) {
                          Logger.getLogger(BuscarFacturaVenta.class.getName()).log(Level.SEVERE, null, ex);
                      }
                   }else{
                      JOptionPane.showMessageDialog(this,"Error. La factura no pudo ser eliminada","Error", JOptionPane.ERROR_MESSAGE); //Tipo de mensaje
                     }
               } 
            
          }
         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cantidad;
    private com.toedter.calendar.JDateChooser desde;
    private javax.swing.JRadioButton facturaRadio;
    private com.toedter.calendar.JDateChooser hasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mostrar;
    private javax.swing.JRadioButton nombreRadio;
    private javax.swing.JTable tfacturas;
    // End of variables declaration//GEN-END:variables
}
