/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemaTienda;

import claseConectar.Dominio;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Point;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Ezenic
 */
public class EstadisticasArticulos extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    Principal p;
    
    public EstadisticasArticulos(Principal p) {
        initComponents();       
        this.p = p;
        cargar(desde.getDate(),hasta.getDate());
        Dominio.centrarDatos(testadistica);
        this.setLocation((this.p.getSize().width/2)-(this.getWidth()/2), (this.p.getSize().height/2)-(this.getHeight()/2));        
        initSucursales();
    }
    
     private void initSucursales() {
            try {
            ResultSet rs = this.p.bd.listarDatosSucursalesTotales();
            while(rs.next())
            {       
                sucursal.addItem(rs.getString("nombre"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testadistica = new javax.swing.JTable();
        gan = new javax.swing.JTextField();
        tot = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cos = new javax.swing.JTextField();
        cant = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        desde = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hasta = new com.toedter.calendar.JDateChooser();
        mostrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        articuloRadio = new javax.swing.JRadioButton();
        articulo = new javax.swing.JTextField();
        sucursalRadio = new javax.swing.JRadioButton();
        sucursal = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ESTADISTICAS DE ARTICULOS");
        setAutoscrolls(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Artículos Venidos"));

        testadistica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Sucursal", "Cantidad Vendida", "Costos", "Ganancia", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        testadistica.getTableHeader().setReorderingAllowed(false);
        testadistica.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                testadisticaMouseMoved(evt);
            }
        });
        testadistica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testadisticaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                testadisticaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                testadisticaMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(testadistica);
        if (testadistica.getColumnModel().getColumnCount() > 0) {
            testadistica.getColumnModel().getColumn(2).setPreferredWidth(300);
            testadistica.getColumnModel().getColumn(2).setMaxWidth(300);
            testadistica.getColumnModel().getColumn(3).setPreferredWidth(300);
            testadistica.getColumnModel().getColumn(3).setMaxWidth(300);
            testadistica.getColumnModel().getColumn(4).setPreferredWidth(300);
            testadistica.getColumnModel().getColumn(4).setMaxWidth(300);
            testadistica.getColumnModel().getColumn(5).setPreferredWidth(300);
            testadistica.getColumnModel().getColumn(5).setMaxWidth(300);
        }

        gan.setEditable(false);
        gan.setEnabled(false);
        gan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganActionPerformed(evt);
            }
        });

        tot.setEnabled(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("TOTAL: ");

        cos.setEditable(false);
        cos.setEnabled(false);

        cant.setEditable(false);
        cant.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gan, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cos, gan, tot});

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Elija la fecha de la venta"));

        desde.setBackground(new java.awt.Color(255, 0, 51));
        desde.setForeground(java.awt.Color.blue);
        desde.setToolTipText("");
        desde.setDate(new Date());
        desde.setMinSelectableDate(new java.util.Date(-62135755099000L));
        desde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                desdeMouseReleased(evt);
            }
        });
        desde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                desdePropertyChange(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jButton1.setText("Exportar a Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Desde");

        jLabel2.setText("Hasta");

        hasta.setDate(new Date());
        hasta.setMinSelectableDate(new java.util.Date(-62135755099000L));
        hasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hastaPropertyChange(evt);
            }
        });

        mostrar.setText("Mostrar todas las ventas");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar las ventas de hoy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 0, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("Filtrar Por:");

        articuloRadio.setText("Articulo");
        articuloRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articuloRadioActionPerformed(evt);
            }
        });

        articulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                articuloKeyTyped(evt);
            }
        });

        sucursalRadio.setText("Sucursal");
        sucursalRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucursalRadioActionPerformed(evt);
            }
        });

        sucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(articuloRadio)
                            .addComponent(sucursalRadio))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(articulo, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(sucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(mostrar)))
                    .addComponent(jButton2))
                .addContainerGap(48, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articuloRadio)
                    .addComponent(articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sucursalRadio)
                    .addComponent(sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testadisticaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testadisticaMouseMoved

    }//GEN-LAST:event_testadisticaMouseMoved

    public void cargar(Date de, Date ha){
   
    String []Registros=new String[6];
    model= (DefaultTableModel) testadistica.getModel();
    model = Dominio.eliminarTabla(model); 
    int ventas=0;
        try {
              String consulta="";
              ResultSet rsArticulos = null;
              String filtros="";
                  if (articuloRadio.isSelected()){
                      filtros+=" and lower(a.nombre) like '%"+articulo.getText().toLowerCase()+"%'";
                  }
                  if (sucursalRadio.isSelected()){
                      filtros+=" and s.nombre ='"+sucursal.getSelectedItem().toString()+"' ";
                  }
                  consulta+="SELECT  a.nombre, s.nombre, Sum(far.cantidad), Sum(far.costo), sum(far.ganancia), sum(far.subtotal) FROM fa as far "
                             +"inner join articulos as a on a.id_articulo = far.id_articulo " 
                             +"inner join facturas as f on f.id_factura = far.id_factura " 
                             +"inner join sucursales as s on s.id_sucursal = f.id_sucursal " 
                             +"where f.eliminado='0' and f.fecha>='"+de+"' and f.fecha<='"+ha+"' "+filtros+ " group by a.nombre, s.nombre order by a.nombre asc;";
                  rsArticulos = this.p.bd.mostrarEstadisticasDeArticulos(consulta); //toma fila por fila      
              float ganancias=0;
              float costos=0;
              float total=0;  
              int cantidad=0;
              while(rsArticulos.next())
              {                
                  Registros[0]= rsArticulos.getString(1); //articulo 
                  Registros[1]= rsArticulos.getString(2); //sucursal
                  cantidad += Integer.parseInt(rsArticulos.getString(3));
                  Registros[2]= rsArticulos.getString(3); //cantidad
                  costos+= Float.parseFloat(rsArticulos.getString(4));
                  Registros[3]= rsArticulos.getString(4); //costos
                  ganancias+= Float.parseFloat(rsArticulos.getString(5));
                  Registros[4]= rsArticulos.getString(5); //ganancia       
                  total+= Float.parseFloat(rsArticulos.getString(6));
                  Registros[5]= rsArticulos.getString(6); //total           
                  model.addRow(Registros);      
              }
              testadistica.setModel(model);    
              cos.setText(Dominio.A2Decimales(Float.toString(costos)));
              gan.setText(Dominio.A2Decimales(Float.toString(ganancias))); 
              tot.setText(Dominio.A2Decimales(Float.toString(total)));
              cant.setText(Integer.toString(cantidad));
        } catch (SQLException ex) {
            Logger.getLogger(EstadisticasArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
  }  
    private void testadisticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testadisticaMouseClicked

       
    }//GEN-LAST:event_testadisticaMouseClicked

    private void testadisticaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testadisticaMouseEntered

    }//GEN-LAST:event_testadisticaMouseEntered

    private void testadisticaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testadisticaMouseExited

    }//GEN-LAST:event_testadisticaMouseExited

    private void desdeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desdeMouseReleased

    }//GEN-LAST:event_desdeMouseReleased

    private void desdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_desdePropertyChange
        if (desde.getDate().after(hasta.getDate())){
            hasta.setDate(desde.getDate());
        }
        cargar(desde.getDate(),hasta.getDate());
    }//GEN-LAST:event_desdePropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if (testadistica.getRowCount()==0){
         JOptionPane.showMessageDialog(this, "Error. La tabla esta vacía.", "Error", JOptionPane.ERROR_MESSAGE);
     }   else{
        //creamos un JFileChooser para elegir donde queremos guardar nuestro archivo
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Guardar Archivo");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
            Thread t=  new Thread(){
                     public void run(){
                          JOptionPane.showMessageDialog(null, "Archivo creado con éxito", "Exportando a Excel. Por favor espere...", JOptionPane.INFORMATION_MESSAGE);
                         }
                   };
            t.start();
            String file = chooser.getSelectedFile().toString().concat(".xlsx");
            XSSFWorkbook excel = new XSSFWorkbook(); //libro excel
            XSSFSheet hoja = excel.createSheet(); //Crea una hoj
            XSSFRow filaPeriodo = hoja.createRow(0); //Creo una fila                     
            filaPeriodo.createCell(0).setCellValue("Periodo");
            filaPeriodo.createCell(1).setCellValue("Desde");
            filaPeriodo.createCell(2).setCellValue(Dominio.formatofechaJCalender.format(desde.getDate()));
            filaPeriodo.createCell(3).setCellValue("Hasta");
            filaPeriodo.createCell(4).setCellValue(Dominio.formatofechaJCalender.format(hasta.getDate()));         
            hoja.createRow(1);
            XSSFRow filaTitulo = hoja.createRow(2); //Creo una fila
            filaTitulo.createCell(0).setCellValue("Artículo");
            filaTitulo.createCell(1).setCellValue("Sucursal");
            filaTitulo.createCell(2).setCellValue("Cantidad vendida");
            filaTitulo.createCell(3).setCellValue("Costos");
            filaTitulo.createCell(4).setCellValue("Ganancia");
            filaTitulo.createCell(5).setCellValue("Total");
            XSSFRow filasDatos;
            int i;
            for (i=0;i<testadistica.getRowCount();i++){          
                filasDatos = hoja.createRow((i+3));
                for (int j=0;j<testadistica.getColumnCount();j++){
                     filasDatos.createCell(j).setCellValue(testadistica.getValueAt(i, j).toString());
                }               
            }           
            XSSFRow filaFinal = hoja.createRow(i+4); //Creo una fila
            filaFinal.createCell(1).setCellValue("TOTAL");
            filaFinal.createCell(2).setCellValue(cant.getText());
            filaFinal.createCell(3).setCellValue(cos.getText());
            filaFinal.createCell(4).setCellValue(gan.getText());
            filaFinal.createCell(5).setCellValue(tot.getText());
   
            try {
                excel.write(new FileOutputStream(file));
                Desktop.getDesktop().open(new File(file));
            } catch (IOException ex) {
                Logger.getLogger(EstadisticasArticulos.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "No se pudo crear el Archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
            t.suspend();
        }
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hastaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_hastaPropertyChange
        if (hasta.getDate().before(desde.getDate())){
            desde.setDate(hasta.getDate());
        }
        cargar(desde.getDate(),hasta.getDate());
    }//GEN-LAST:event_hastaPropertyChange

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        try {
            ResultSet rsFecha = this.p.bd.obtenerFechaMinimaYMaximaDeFacturas(); //toma fila por fila
            if (rsFecha.next()){
                desde.setDate(Dominio.formatofechaBD.parse(rsFecha.getString(1)));
                hasta.setDate(Dominio.formatofechaBD.parse(rsFecha.getString(2)));
                cargar(desde.getDate(),hasta.getDate());
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(EstadisticasArticulos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(EstadisticasArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mostrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       desde.setDate(new Date());
       hasta.setDate(new Date());
       cargar(desde.getDate(),hasta.getDate());
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void articuloRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articuloRadioActionPerformed

           cargar(desde.getDate(),hasta.getDate()); 
        
    }//GEN-LAST:event_articuloRadioActionPerformed

    private void articuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_articuloKeyTyped
        if (articuloRadio.isSelected()){
           cargar(desde.getDate(),hasta.getDate()); 
        }
    }//GEN-LAST:event_articuloKeyTyped

    private void ganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ganActionPerformed

    private void sucursalRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucursalRadioActionPerformed
         cargar(desde.getDate(),hasta.getDate()); 
    }//GEN-LAST:event_sucursalRadioActionPerformed

    private void sucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucursalActionPerformed
        if (sucursalRadio.isSelected()){
           cargar(desde.getDate(),hasta.getDate()); 
        } 
    }//GEN-LAST:event_sucursalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField articulo;
    private javax.swing.JRadioButton articuloRadio;
    private javax.swing.JTextField cant;
    private javax.swing.JTextField cos;
    private com.toedter.calendar.JDateChooser desde;
    private javax.swing.JTextField gan;
    private com.toedter.calendar.JDateChooser hasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mostrar;
    private javax.swing.JComboBox<String> sucursal;
    private javax.swing.JRadioButton sucursalRadio;
    private javax.swing.JTable testadistica;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables
  
 }
