/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemaTienda;

import claseConectar.Dominio;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Ezenic
 */
public class IngresoMisClientes extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    Principal p;
    
    public IngresoMisClientes( Principal p) {
       
            initComponents();
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );
            tclientes.setDefaultRenderer(String.class, centerRenderer);
            
            this.p = p;
            cargar("");  
            this.setLocation((p.getSize().width/2)-(this.getWidth()/2), (p.getSize().height/2)-(this.getHeight()/2));
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        mostrar = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        crollpane = new javax.swing.JScrollPane();
        tclientes = new javax.swing.JTable();
        cantidad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("REGISTRO DE MIS CLIENTES");
        setName(""); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        mostrar.setText("Mostrar Todos");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });

        jLabel2.setText("BUSCAR");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Mis Clientes"));

        tclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Cliente", "Nombre y Apellido", "Teléfono", "Correo Electrónico", "Saldo a Favor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tclientes.getTableHeader().setReorderingAllowed(false);
        tclientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tclientesMouseMoved(evt);
            }
        });
        tclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tclientesMouseClicked(evt);
            }
        });
        tclientes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tclientesComponentShown(evt);
            }
        });
        crollpane.setViewportView(tclientes);

        cantidad.setText("Cantidad de Clientes: 0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crollpane)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cantidad)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(crollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Cliente"));

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre y Apellido");

        telefono.setColumns(5);
        telefono.setEnabled(false);
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Teléfono");

        nombre.setColumns(5);
        nombre.setEnabled(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });

        jLabel4.setText("Correo Electrónico");

        correo.setColumns(5);
        correo.setEnabled(false);
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });
        correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                correoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correoKeyTyped(evt);
            }
        });

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/16 (Save).jpg"))); // NOI18N
        guardar.setText("Guardar");
        guardar.setEnabled(false);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/16 (Save).jpg"))); // NOI18N
        actualizar.setText("Actualizar");
        actualizar.setEnabled(false);
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(243, 243, 243)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(modificar)
                        .addGap(13, 13, 13)
                        .addComponent(actualizar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modificar)
                            .addComponent(actualizar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevo)
                            .addComponent(cancelar))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mostrar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void principal(){
      nuevo.setEnabled(true);
      nombre.setEnabled(false);
      nombre.setText("");
      telefono.setText("");
      correo.setText("");
      telefono.setEnabled(false);
      guardar.setEnabled(false);
      correo.setEnabled(false);
      buscar.setEnabled(true);
      mostrar.setEnabled(true);
      modificar.setEnabled(true);
      eliminar.setEnabled(true);
      actualizar.setEnabled(false);
      tclientes.setEnabled(true);
      cancelar.setEnabled(false);
    }
    
    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    
    
    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
          cancelar.setEnabled(true);
          nuevo.setEnabled(false);
          guardar.setEnabled(true);
          nombre.requestFocus();
          nombre.setEnabled(true);
          nombre.setText("");
          telefono.setEnabled(true);
          telefono.setText("");
          correo.setEnabled(true);
          correo.setText("");
          tclientes.setEnabled(false);
          eliminar.setEnabled(false);
          modificar.setEnabled(false);
          buscar.setEnabled(false);
          mostrar.setEnabled(false);

    
        
    }//GEN-LAST:event_nuevoActionPerformed

     private  void cargar(String valor){
     tclientes.getColumnModel().getColumn(1).setCellRenderer(new TableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, final Object value, boolean arg2,
                boolean arg3, int arg4, int arg5) {
            final JLabel lab = new JLabel("<html><a href=\"" + value + "\">" + value + "</a>");
            return lab;
        }
    });
    String []Registros=new String[5];
    model= (DefaultTableModel) tclientes.getModel();
    model = Dominio.eliminarTabla(model); 
        try {             
              ResultSet rs = this.p.bd.listarDatosMisClientes(valor);
              while(rs.next())
              {
                  Registros[0]= rs.getString("id_mcliente");
                  Registros[1]= rs.getString("nombre");   
                  Registros[2]= rs.getString("telefono");  
                  Registros[3]= rs.getString("correo");  
                  Registros[4]= rs.getString("saldo_favor");  
                  model.addRow(Registros);
              }
              tclientes.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(IngresoMisClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    cantidad.setText("Cantidad de Clientes: "+tclientes.getRowCount());
   // tclientes = Dominio.centrarDatos(tclientes);
    
     
  }
    

    
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
       nuevoCliente(); 
    }//GEN-LAST:event_guardarActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed

    }//GEN-LAST:event_telefonoActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
      cargar(buscar.getText()) ;      // TODO add your handling code here:
    }//GEN-LAST:event_buscarKeyReleased

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
      cargar("");        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarActionPerformed

    private void tclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tclientesMouseClicked
         int col = tclientes.columnAtPoint(new Point(evt.getX(), evt.getY()));
         if (col==1){
             try {
                 int fila = tclientes.rowAtPoint(new Point(evt.getX(), evt.getY()));
                 String id_cliente =model.getValueAt(fila,0).toString();
                 String nombre =model.getValueAt(fila,1).toString();
                 String tel =model.getValueAt(fila,2).toString();
                 String correo =model.getValueAt(fila,3).toString();
                 FacturasCliente  fc = new FacturasCliente(this.p,id_cliente,nombre,tel,correo);
                 this.p.escritorio.add(fc);
                 this.p.escritorio.setSelectedFrame(fc);
                 fc.show();
                 fc.setMaximum(true);   
                 tclientes.setModel(model);
             } catch (PropertyVetoException ex) {
                 Logger.getLogger(IngresoMisClientes.class.getName()).log(Level.SEVERE, null, ex);
             }                      
          }    
         
       if (evt.getClickCount() == 2){
            modificarCliente();
        } 
  
    }//GEN-LAST:event_tclientesMouseClicked

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
          principal();
    }//GEN-LAST:event_cancelarActionPerformed

    private void tclientesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tclientesComponentShown

    }//GEN-LAST:event_tclientesComponentShown

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
      
        if (tclientes.getSelectedRow()== -1) {
           JOptionPane.showMessageDialog(this,"No ha seleccionado ningún cliente","Advertencia", JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
       }else{
            if (JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(this, "Desea eliminar al cliente seleccionado junto con sus datos?" )){
              int fila= tclientes.getSelectedRow();
              String cod="";
              cod=tclientes.getValueAt(fila, 0).toString();        
              int n=this.p.bd.eliminarMiCliente(cod);
                if(n>0){
                    JOptionPane.showMessageDialog(this, "Cliente eliminado con Exito.");
                    cargar("");
              
                }else{
                    JOptionPane.showMessageDialog(this, "No se ha podido eliminar al cliente.");
                }   
                principal();
        } 
        }
    }//GEN-LAST:event_eliminarActionPerformed

    
    private void modificarCliente(){
                  
        if (tclientes.getSelectedRow()== -1) {
           JOptionPane.showMessageDialog(this,"No ha seleccionado ningún cliente","Advertencia", JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
       }else{
              cancelar.setEnabled(true);
              nuevo.setEnabled(false);
              guardar.setEnabled(true);
              nombre.requestFocus();
              telefono.setEnabled(true);
              nombre.setEnabled(true);
              correo.setEnabled(true);
              tclientes.setEnabled(false);
              eliminar.setEnabled(false);
              guardar.setEnabled(false);
              modificar.setEnabled(false);
              actualizar.setEnabled(true);
              buscar.setEnabled(false);
              mostrar.setEnabled(false);
              int fila= tclientes.getSelectedRow(); 
              String nom =  tclientes.getValueAt(fila, 1).toString();
              String tel =  tclientes.getValueAt(fila, 2).toString();
              String cor =  tclientes.getValueAt(fila, 3).toString();
              telefono.setText(tel);  
              correo.setText(cor); 
              nombre.setText(nom); 
        }
    }
    
    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
           modificarCliente();
    }//GEN-LAST:event_modificarActionPerformed

    
   private void actualizarCliente(){
      if (validarDatos()){
              int fila= tclientes.getSelectedRow();
              String cod="";
              cod=tclientes.getValueAt(fila, 0).toString(); 
              int n=this.p.bd.modificarMiCliente(nombre.getText(),telefono.getText(),correo.getText(),cod,this);
              if(n>0){
                 JOptionPane.showMessageDialog(null, "Cliente modificado con Exito.");
                 cargar("");
                 principal();
              }
        }
   }
    
    
    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
           actualizarCliente();
    }//GEN-LAST:event_actualizarActionPerformed

    private boolean validarDatos(){
     boolean validar = false;
     String texto=nombre.getText();
     if(texto.length()==0){          
            JOptionPane.showMessageDialog(this,"El campo "+jLabel1.getText() +" no debe ser vacio","Advertencia", JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
      }
     else
       {
           validar=true;
       }
       return validar;
       } 
 
    
    private void nuevoCliente() {
       if (validarDatos()){
           int n=this.p.bd.agregarMiCliente(nombre.getText(),telefono.getText(),correo.getText(),this);
           if(n>0){
               JOptionPane.showMessageDialog(null, "Cliente Guardado con Exito");
               principal();
           }
           cargar(""); 
        }
    }
    
    private void telefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyReleased
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if (actualizar.isEnabled()){
                actualizarCliente();
            }
            if (guardar.isEnabled()){
                nuevoCliente();
            }
        } 
      
    }//GEN-LAST:event_telefonoKeyReleased

    //Limitar la cantidad de caracteres
    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped

        if (telefono.getText().length() == Dominio.DOM_NOMBRES){
            evt.consume();
        }
    }//GEN-LAST:event_telefonoKeyTyped

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyReleased
     if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if (actualizar.isEnabled()){
               actualizarCliente();
            }
            if (guardar.isEnabled()){
                nuevoCliente();
            }
}
    }//GEN-LAST:event_nombreKeyReleased

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
         if (nombre.getText().length() == Dominio.DOM_NOMBRES){
            evt.consume();
        }
    }//GEN-LAST:event_nombreKeyTyped

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void correoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoKeyReleased
     if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if (actualizar.isEnabled()){
               actualizarCliente();
            }
            if (guardar.isEnabled()){
                nuevoCliente();
            }
}        // TODO add your handling code here:
    }//GEN-LAST:event_correoKeyReleased

    private void correoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoKeyTyped
        if (correo.getText().length() == Dominio.DOM_NOMBRES){
            evt.consume();
        }
    }//GEN-LAST:event_correoKeyTyped

    private void tclientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tclientesMouseMoved
            int col = tclientes.columnAtPoint(new Point(evt.getX(), evt.getY()));
            if (col == 1) {             
                tclientes.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }else{
                tclientes.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }        // TODO add your handling code here:
    }//GEN-LAST:event_tclientesMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel cantidad;
    private javax.swing.JTextField correo;
    private javax.swing.JScrollPane crollpane;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton modificar;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton nuevo;
    private javax.swing.JTable tclientes;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables




 
}
