/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaTienda;

import claseConectar.Dominio;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A309917
 */
public class Sucursales extends javax.swing.JInternalFrame {

   
    DefaultTableModel model;
    Principal p;
   
    public Sucursales( Principal p) {
       
            initComponents();
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );
            tsucursales.setDefaultRenderer(String.class, centerRenderer);
            
            this.p = p;
            cargar();  
            //this.setLocation((p.getSize().width/2)-(this.getWidth()/2), (p.getSize().height/2)-(this.getHeight()/2));
   
    }
    
         private  void cargar(){
                String []Registros=new String[2];
                model= (DefaultTableModel) tsucursales.getModel();
                model = Dominio.eliminarTabla(model); 
                    try {             
                          ResultSet rs = this.p.bd.listarDatosSucursales();
                          while(rs.next())
                          {
                              Registros[0]= rs.getString("id_sucursal");
                              Registros[1]= rs.getString("nombre");                   
                              model.addRow(Registros);
                          }
                          tsucursales.setModel(model);
                    } catch (SQLException ex) {
                        Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                cantidad.setText("Cantidad de Sucursales: " + tsucursales.getRowCount());            
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        agregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        crollpane = new javax.swing.JScrollPane();
        tsucursales = new javax.swing.JTable();
        cantidad = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPopupMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPopupMenu1.setLabel("");

        jMenuItem1.setText("Eliminar Sucursal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setClosable(true);
        setMaximizable(true);
        setTitle("SUCURSALES");

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/16 (Save).jpg"))); // NOI18N
        agregar.setText("Agregar Nueva Sucursal");
        agregar.setEnabled(false);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Sucursales"));

        tsucursales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tsucursales.setComponentPopupMenu(jPopupMenu1);
        tsucursales.getTableHeader().setReorderingAllowed(false);
        tsucursales.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tsucursalesMouseMoved(evt);
            }
        });
        tsucursales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tsucursalesMouseClicked(evt);
            }
        });
        tsucursales.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tsucursalesComponentShown(evt);
            }
        });
        crollpane.setViewportView(tsucursales);

        cantidad.setText("Cantidad de Sucursales: 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 1548, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cantidad)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(cantidad)
                .addGap(9, 9, 9))
        );

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreKeyReleased(evt);
            }
        });

        jLabel1.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(agregar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tsucursalesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsucursalesMouseMoved
     
    }//GEN-LAST:event_tsucursalesMouseMoved

    private void tsucursalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsucursalesMouseClicked
     
    }//GEN-LAST:event_tsucursalesMouseClicked

    private void tsucursalesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tsucursalesComponentShown

    }//GEN-LAST:event_tsucursalesComponentShown

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
         if (this.p.bd.agregarSucursal(nombre.getText()) == 0) {
              JOptionPane.showMessageDialog(this,"La sucursal con nombre "+nombre.getText()+ " ya existe.","Advertencia", JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
         }else {
             nombre.setText("");
             agregar.setEnabled(false);
             cargar();     
         };               
    }//GEN-LAST:event_agregarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (tsucursales.getSelectedRow()== -1){
            JOptionPane.showMessageDialog(this,"No ha seleccionado ningún item","Error", JOptionPane.ERROR_MESSAGE); //Tipo de mensaje
        }else{
            model =  (DefaultTableModel) tsucursales.getModel();
            int[] arrayElementos = tsucursales.getSelectedRows();
            for (int i=0; i< arrayElementos.length;i++){             
               String idSucursal =model.getValueAt(arrayElementos[i], 0).toString();
               this.p.bd.eliminarSucursal(idSucursal);
            }        
            cargar();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyReleased
        if (nombre.getText().isEmpty()){
            agregar.setEnabled(false);
        }else {
            agregar.setEnabled(true); 
        }
    }//GEN-LAST:event_nombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel cantidad;
    private javax.swing.JScrollPane crollpane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tsucursales;
    // End of variables declaration//GEN-END:variables
}
